#!/usr/bin/env python
# -*- coding: utf-8 -*-
# generated by wxGlade 0.6.3 on Mon Mar  8 21:11:40 2010

import wx

# begin wxGlade: extracode
# end wxGlade



class ConnectFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: ConnectFrame.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.label_1 = wx.StaticText(self, -1, "Port")
        self.text_ctrl_1 = wx.TextCtrl(self, -1, "/dev/ttyS0")
        self.label_2 = wx.StaticText(self, -1, "Baudrate")
        self.text_ctrl_2 = wx.TextCtrl(self, -1, "115200")
        self.btnCancel = wx.Button(self, -1, "Cancel")
        self.btnConnect = wx.Button(self, -1, "Connect")

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.btnCancelHandler, self.btnCancel)
        self.Bind(wx.EVT_BUTTON, self.btnConnectHandler, self.btnConnect)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: ConnectFrame.__set_properties
        self.SetTitle("frame_2")
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: ConnectFrame.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        sizer_2 = wx.BoxSizer(wx.HORIZONTAL)
        grid_sizer_1 = wx.GridSizer(2, 2, 0, 0)
        grid_sizer_1.Add(self.label_1, 0, wx.ALL|wx.ADJUST_MINSIZE, 3)
        grid_sizer_1.Add(self.text_ctrl_1, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1.Add(self.label_2, 0, wx.ALL|wx.ADJUST_MINSIZE, 3)
        grid_sizer_1.Add(self.text_ctrl_2, 0, wx.ADJUST_MINSIZE, 0)
        sizer_1.Add(grid_sizer_1, 1, wx.EXPAND, 0)
        sizer_2.Add(self.btnCancel, 0, wx.ADJUST_MINSIZE, 0)
        sizer_2.Add((20, 20), 0, wx.ADJUST_MINSIZE, 0)
        sizer_2.Add(self.btnConnect, 0, wx.ADJUST_MINSIZE, 0)
        sizer_1.Add(sizer_2, 1, wx.TOP|wx.BOTTOM|wx.ALIGN_CENTER_HORIZONTAL, 3)
        self.SetSizer(sizer_1)
        sizer_1.Fit(self)
        self.Layout()
        # end wxGlade

    def btnCancelHandler(self, event): # wxGlade: ConnectFrame.<event_handler>
        print "Event handler `btnCancelHandler' not implemented!"
        event.Skip()

    def btnConnectHandler(self, event): # wxGlade: ConnectFrame.<event_handler>
        print "Event handler `btnConnectHandler' not implemented!"
        event.Skip()

# end of class ConnectFrame