#!/usr/bin/env python
# -*- coding: utf-8 -*-
# generated by wxGlade 0.6.3 on Tue Mar  9 16:20:24 2010

import wx

# begin wxGlade: extracode
# end wxGlade



class myNotebook(wx.Notebook):
    def __init__(self, *args, **kwds):
        # begin wxGlade: myNotebook.__init__
        kwds["style"] = 0
        wx.Notebook.__init__(self, *args, **kwds)
        self.notebook_2_pane_1 = wx.Panel(self, -1)
        self.label_2 = wx.StaticText(self.notebook_2_pane_1, -1, "Logging")
        self.label_3 = wx.StaticText(self.notebook_2_pane_1, -1, "Data Folder")
        self.text_ctrl_1 = wx.TextCtrl(self.notebook_2_pane_1, -1, "")
        self.checkbox_1 = wx.CheckBox(self.notebook_2_pane_1, -1, "enabled")
        self.label_3_copy = wx.StaticText(self.notebook_2_pane_1, -1, "Data Folder")
        self.text_ctrl_2 = wx.TextCtrl(self.notebook_2_pane_1, -1, "")
        self.static_line_1 = wx.StaticLine(self.notebook_2_pane_1, -1)
        self.label_2_copy = wx.StaticText(self.notebook_2_pane_1, -1, "Histogramm")
        self.label_3_copy_1_copy = wx.StaticText(self.notebook_2_pane_1, -1, "Number of Bins")
        self.text_ctrl_1_copy_copy = wx.TextCtrl(self.notebook_2_pane_1, -1, "")
        self.button_1_copy = wx.Button(self.notebook_2_pane_1, -1, "Fit")
        self.label_3_copy_1 = wx.StaticText(self.notebook_2_pane_1, -1, "x Minimum")
        self.text_ctrl_1_copy = wx.TextCtrl(self.notebook_2_pane_1, -1, "")
        self.button_1 = wx.Button(self.notebook_2_pane_1, -1, "Draw")
        self.label_3_copy_copy = wx.StaticText(self.notebook_2_pane_1, -1, "x Maximum")
        self.text_ctrl_2_copy = wx.TextCtrl(self.notebook_2_pane_1, -1, "")
        self.static_line_2 = wx.StaticLine(self.notebook_2_pane_1, -1)
        self.label_2_copy_copy = wx.StaticText(self.notebook_2_pane_1, -1, "Velocity")
        self.panel_1 = wx.Panel(self.notebook_2_pane_1, -1)
        self.panel_2 = wx.Panel(self.notebook_2_pane_1, -1)
        self.button_1_copy_copy = wx.Button(self.notebook_2_pane_1, -1, "Fit")
        self.label_3_copy_1_copy_1 = wx.StaticText(self.notebook_2_pane_1, -1, "x Minimum")
        self.text_ctrl_1_copy_copy_1 = wx.TextCtrl(self.notebook_2_pane_1, -1, "")
        self.button_1_copy_1 = wx.Button(self.notebook_2_pane_1, -1, "Draw")
        self.label_3_copy_copy_copy = wx.StaticText(self.notebook_2_pane_1, -1, "x Maximum")
        self.text_ctrl_2_copy_copy = wx.TextCtrl(self.notebook_2_pane_1, -1, "")
        self.static_line_3 = wx.StaticLine(self.notebook_2_pane_1, -1)
        self.txtArea = wx.TextCtrl(self.notebook_2_pane_1, -1, "Open Mouse Speed - Use a Mouse Sensor to meassure low Speeds", style=wx.TE_MULTILINE)

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.OnFitHisto, self.button_1_copy)
        self.Bind(wx.EVT_BUTTON, self.OnDrawHisto, self.button_1)
        self.Bind(wx.EVT_BUTTON, self.OnFitVel, self.button_1_copy_copy)
        self.Bind(wx.EVT_BUTTON, self.OnDrawVel, self.button_1_copy_1)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: myNotebook.__set_properties
        self.AddPage(self.notebook_2_pane_1, "Meassurement")
        self.label_2.SetFont(wx.Font(10, wx.DEFAULT, wx.NORMAL, wx.BOLD, 0, ""))
        self.checkbox_1.SetValue(1)
        self.label_2_copy.SetFont(wx.Font(10, wx.DEFAULT, wx.NORMAL, wx.BOLD, 0, ""))
        self.label_2_copy_copy.SetFont(wx.Font(10, wx.DEFAULT, wx.NORMAL, wx.BOLD, 0, ""))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: myNotebook.__do_layout
        sizerOne = wx.BoxSizer(wx.VERTICAL)
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        grid_sizer_1_copy_copy = wx.GridSizer(3, 3, 0, 0)
        grid_sizer_1_copy = wx.GridSizer(3, 3, 0, 0)
        grid_sizer_1 = wx.GridSizer(3, 3, 0, 0)
        grid_sizer_1.Add(self.label_2, 0, wx.ALIGN_CENTER_HORIZONTAL|wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 0)
        grid_sizer_1.Add(self.label_3, 0, wx.ALIGN_CENTER_HORIZONTAL|wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 0)
        grid_sizer_1.Add(self.text_ctrl_1, 0, wx.ALIGN_CENTER_HORIZONTAL|wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 0)
        grid_sizer_1.Add(self.checkbox_1, 0, wx.ALIGN_CENTER_HORIZONTAL|wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 0)
        grid_sizer_1.Add(self.label_3_copy, 0, wx.ALIGN_CENTER_HORIZONTAL|wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 0)
        grid_sizer_1.Add(self.text_ctrl_2, 0, wx.ALIGN_CENTER_HORIZONTAL|wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 0)
        sizer_1.Add(grid_sizer_1, 1, wx.EXPAND, 0)
        sizer_1.Add(self.static_line_1, 0, wx.EXPAND, 0)
        grid_sizer_1_copy.Add(self.label_2_copy, 0, wx.ALIGN_CENTER_HORIZONTAL|wx.ALIGN_CENTER_VERTICAL, 0)
        grid_sizer_1_copy.Add(self.label_3_copy_1_copy, 0, wx.ALIGN_CENTER_HORIZONTAL|wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 0)
        grid_sizer_1_copy.Add(self.text_ctrl_1_copy_copy, 0, wx.ALIGN_CENTER_HORIZONTAL|wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 0)
        grid_sizer_1_copy.Add(self.button_1_copy, 0, wx.ALIGN_CENTER_HORIZONTAL|wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 0)
        grid_sizer_1_copy.Add(self.label_3_copy_1, 0, wx.ALIGN_CENTER_HORIZONTAL|wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 0)
        grid_sizer_1_copy.Add(self.text_ctrl_1_copy, 0, wx.ALIGN_CENTER_HORIZONTAL|wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 0)
        grid_sizer_1_copy.Add(self.button_1, 0, wx.ALIGN_CENTER_HORIZONTAL|wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 0)
        grid_sizer_1_copy.Add(self.label_3_copy_copy, 0, wx.ALIGN_CENTER_HORIZONTAL|wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 0)
        grid_sizer_1_copy.Add(self.text_ctrl_2_copy, 0, wx.ALIGN_CENTER_HORIZONTAL|wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 0)
        sizer_1.Add(grid_sizer_1_copy, 1, wx.EXPAND, 0)
        sizer_1.Add(self.static_line_2, 0, wx.EXPAND, 0)
        grid_sizer_1_copy_copy.Add(self.label_2_copy_copy, 0, wx.ALIGN_CENTER_HORIZONTAL|wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 0)
        grid_sizer_1_copy_copy.Add(self.panel_1, 1, wx.EXPAND, 0)
        grid_sizer_1_copy_copy.Add(self.panel_2, 1, wx.EXPAND, 0)
        grid_sizer_1_copy_copy.Add(self.button_1_copy_copy, 0, wx.ALIGN_CENTER_HORIZONTAL|wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 0)
        grid_sizer_1_copy_copy.Add(self.label_3_copy_1_copy_1, 0, wx.ALIGN_CENTER_HORIZONTAL|wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 0)
        grid_sizer_1_copy_copy.Add(self.text_ctrl_1_copy_copy_1, 0, wx.ALIGN_CENTER_HORIZONTAL|wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 0)
        grid_sizer_1_copy_copy.Add(self.button_1_copy_1, 0, wx.ALIGN_CENTER_HORIZONTAL|wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 0)
        grid_sizer_1_copy_copy.Add(self.label_3_copy_copy_copy, 0, wx.ALIGN_CENTER_HORIZONTAL|wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 0)
        grid_sizer_1_copy_copy.Add(self.text_ctrl_2_copy_copy, 0, wx.ALIGN_CENTER_HORIZONTAL|wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 0)
        sizer_1.Add(grid_sizer_1_copy_copy, 1, wx.EXPAND, 0)
        sizer_1.Add(self.static_line_3, 0, wx.EXPAND, 0)
        sizerOne.Add(sizer_1, 1, wx.EXPAND, 0)
        sizerOne.Add(self.txtArea, 0, wx.EXPAND|wx.ADJUST_MINSIZE, 0)
        self.notebook_2_pane_1.SetSizer(sizerOne)
        # end wxGlade

    def OnFitHisto(self, event): # wxGlade: myNotebook.<event_handler>
        print "Event handler `OnFitHisto' not implemented!"
        event.Skip()

    def OnDrawHisto(self, event): # wxGlade: myNotebook.<event_handler>
        print "Event handler `OnDrawHisto' not implemented!"
        event.Skip()

    def OnFitVel(self, event): # wxGlade: myNotebook.<event_handler>
        print "Event handler `OnFitVel' not implemented!"
        event.Skip()

    def OnDrawVel(self, event): # wxGlade: myNotebook.<event_handler>
        print "Event handler `OnDrawVel' not implemented!"
        event.Skip()

# end of class myNotebook


class MainFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MainFrame.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        
        # Menu Bar
        self.menubar = wx.MenuBar()
        wxglade_tmp_menu = wx.Menu()
        wxglade_tmp_menu.Append(wx.NewId(), "Connect", "", wx.ITEM_NORMAL)
        wxglade_tmp_menu.AppendSeparator()
        wxglade_tmp_menu.Append(wx.NewId(), "Quit", "", wx.ITEM_NORMAL)
        self.menubar.Append(wxglade_tmp_menu, "File")
        wxglade_tmp_menu = wx.Menu()
        wxglade_tmp_menu.Append(wx.NewId(), "About", "", wx.ITEM_NORMAL)
        self.menubar.Append(wxglade_tmp_menu, "Help")
        self.SetMenuBar(self.menubar)
        # Menu Bar end
        self.statusbar = self.CreateStatusBar(1, 0)
        self.tabsMain = myNotebook(self, -1)

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_MENU, self.menuConnectHandler, id=-1)
        self.Bind(wx.EVT_MENU, self.menuQuitHandler, id=-1)
        self.Bind(wx.EVT_MENU, self.menuAboutHandler, id=-1)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MainFrame.__set_properties
        self.SetTitle("openMouseSpeed")
        self.SetSize((375, 540))
        self.statusbar.SetStatusWidths([-1])
        # statusbar fields
        statusbar_fields = ["Welcome to openMouseSpeed 0.1a"]
        for i in range(len(statusbar_fields)):
            self.statusbar.SetStatusText(statusbar_fields[i], i)
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MainFrame.__do_layout
        sizerMain = wx.BoxSizer(wx.VERTICAL)
        sizerMain.Add(self.tabsMain, 1, wx.EXPAND, 0)
        self.SetSizer(sizerMain)
        self.Layout()
        self.SetSize((375, 540))
        # end wxGlade

    def menuConnectHandler(self, event): # wxGlade: MainFrame.<event_handler>
        print "Event handler `menuConnectHandler' not implemented!"
        event.Skip()

    def menuQuitHandler(self, event): # wxGlade: MainFrame.<event_handler>
        print "Event handler `menuQuitHandler' not implemented!"
        event.Skip()

    def menuAboutHandler(self, event): # wxGlade: MainFrame.<event_handler>
        print "Event handler `menuAboutHandler' not implemented!"
        event.Skip()

# end of class MainFrame


if __name__ == "__main__":
    app = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    mainFrame = MainFrame(None, -1, "")
    app.SetTopWindow(mainFrame)
    mainFrame.Show()
    app.MainLoop()
